### ISSUE TITLE
File management

### ISSUE THREAD

**Issue by anxiousmodernman** [anxiousmodernman/hpt#10]
File is going to be a workhorse, as many state-applys in our design create files and directories as a side effect (for instance, cloning or creating a user's home), but rely on file to delete/cleanup/remove the things they created.

This seems like the right choice, if we think that removing files automatically is risky. In the example of a user's home directory, this seems true. We might still want files that are sitting in their home, so merely removing "someuser" from the system should not run `rm -rf /home/someuser` as a side effect. We want the filesystem side effect on user creation, not removal.

A file config block looks like this. Here we fetch a file from our bucket and put it on a destination path.

```toml
[[file]]
dest = "/etc/systemd/system/ourservice.service"
src = "bkt://ourservice.service"
perms = 640
```

Here we declare the removal of the same file. If the file is absent upon apply, it's a no op.

```toml
[[file]]
path = "/etc/systemd/system/ourservice.service"
src = "bkt://ourservice.service"
remove = true
```

Directories are files, too. And `remove` should work with directories.

```toml
[[file]]
path = "/opt/sourcecode"
dir = true
```

The choice of systemd as an example illustrates that the old saying is true: everything is truly a file in unix. A great deal of system config could be implemented with the ability to write files and run commands. 

### Templates

Templates are nice. We should support them eventually. We should be careful to keep a generic template execution interface, so we can swap template languages. We could start with Go's `text/template` for development, but we should support mustache at least and perhaps something jinja-ish, too.

```toml
[[file]]
path = "/opt/foo/conf.yml"
src = '${data("foodata")}'  # we would need to add a func "data" to hil
dir = true

[data.foodata]
blah1 = 'env("BLAH1")'
blah2 = 'env("BLAH2")'
```

This is speculative. We might be able to us [Hashicorp Interpolation Language](https://github.com/hashicorp/hil) ("hil") for a string substitution DSL that would let us grab env vars and reference other data in a config. We would need to figure out how to extend it with new functions.

Note the use of single quotes. This lets us make a TOML string that _contains_ double quotes. [See here](https://github.com/toml-lang/toml#string).

### Archives (.tar, .zip)

It would be convenient to support expanding compressed archives into a directory tree with `extract = true`.

```toml
[[file]]
path = "/opt/sourcecode"
src = "bkt://sourcecode.tar.gz"
extract = true
```
