### ISSUE TITLE
Exec: command execution

### ISSUE THREAD

**Issue by anxiousmodernman** [anxiousmodernman/hpt#12]
We want to support two syntaxes

```toml
[[exec]]
cmd = "rm"
args = ["-rf", "/"]
```
```toml
[[exec]]
script = '''
rm -rf /
echo oops
'''
```
We should be able to set the user under whom the command executes, and the working diretory.
