### ISSUE TITLE
Users and groups

### ISSUE THREAD

**Issue by anxiousmodernman** [anxiousmodernman/hpt#2]
We need to implement management for groups and users. 

### User ops

* [x] create user
* [x] remove user
* [ ] add user to group
* [ ] remove user from group
* [x] test if user exists
* [ ] test group membership

### Group ops

* [ ] create group
* [ ] delete group
* [ ] no password sudo on
* [ ] no password sudo off
* [ ] test if group exists

One difficulty is editing **/etc/sudoers**, I'm not aware of a pure go parser for this format. We can probably get away with regular expressions or appending to the file.

A full declarative block example for `user`:

```toml
[[user]]
# name is passed to useradd
name = "coleman"
# home is created, if set
home = "/home/coleman"
# groups are expected to exist, or be declared in a [[group]] block
groups = ["wheel", "something"]
# files must be resolvers; resolvers let us deliver files over the network
ssh_public_key = "bucket1://ssh-keys/someone.pub"
ssh_private_key = "bucket1://ssh-keys/someone"
```

Two example `group` blocks:

```toml
[[group]]
# a custom group
name = "something"
gid = "1001"

[[group]]
# a modification to the system-provided wheel group
name = "wheel"
# this is an edit to /etc/sudoers
passwordless_sudo = true
```
