### ISSUE TITLE
Clone repos

### ISSUE THREAD

**Issue by anxiousmodernman** [anxiousmodernman/hpt#5]
We want a way to clone repos to disk with git.

Auth can be done with ssh keys. We could support http basic auth later.

```toml
[[clone]]
URL = "https://foo"
User = "???" # TODO review the go-git library's ssh internals
Dest = "/opt/local/path"  # destination dir
Key = "bucket://key"  # a resolver
```

Questions:
* do we need to provide a way to remove repos via `[[clone]]` or can we rely on `[[file]]`
